### ISSUE TITLE
我 go build riot的时候，发现google.golang.org/grpc有错误

### ISSUE THREAD

**Issue by eruca** [laohanlinux/riot#4]
`# google.golang.org/grpc/transport
../../../google.golang.org/grpc/transport/handler_server.go:209: undefined: http2.TrailerPrefix
../../../google.golang.org/grpc/transport/http2_client.go:840: undefined: http2.MetaHeadersFrame
../../../google.golang.org/grpc/transport/http2_client.go:943: undefined: http2.MetaHeadersFrame
../../../google.golang.org/grpc/transport/http2_server.go:145: undefined: http2.MetaHeadersFrame
../../../google.golang.org/grpc/transport/http2_server.go:281: undefined: http2.MetaHeadersFrame
../../../google.golang.org/grpc/transport/http_util.go:382: f.fr.ReadMetaHeaders undefined (type *http2.Framer has no field or method ReadMetaHeaders)
../../../google.golang.org/grpc/transport/http_util.go:512: f.fr.ErrorDetail undefined (type *http2.Framer has no field or method ErrorDetail)`
我是今天下载的库，是不是更新了，导致不兼容

**Comment by laohanlinux** [comment]
可能是go版本的问题，你用 go1.7.1版本试一下
